services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: cyphera
      POSTGRES_DB: cyphera_demo
      CYPHERA_POLICY_FILE: /etc/cyphera/cyphera.yaml
    volumes:
      - ./config/cyphera.yaml:/etc/cyphera/cyphera.yaml:ro
